version: "3"
services:
  cms-api:
    image: optiwariindia/php-server:1.0.0
    container_name: cms-api
    volumes:
      - ./api:/var/www
    networks:
      - publicweb
      - mysql
    restart: unless-stopped
  cms-web:
    image: optiwariindia/react-server:1.0.0
    container_name: cms-web
    volumes:
      - ./web/src:/src/
      - ./web/public:/public/
    networks:
      - publicweb
    restart: unless-stopped
    environment:
    - WDS_SOCKET_PORT=80
networks:
  publicweb:
    external: true
  mysql:
    external: true